
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-deployment
spec:
  selector:
    matchLabels:
      app: kibana
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: kibana
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - kibana
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana-oss:6.5.4
        env:
        - name: SERVER_NAME
          value: kibana-service
        - name: ELASTICSEARCH_URL
          value: http://esproxy-service:9200
        livenessProbe:
          httpGet:
            path: /status
            port: 5601
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /status
            port: 5601
        ports:
        - containerPort: 5601
        resources: {}