apiVersion: v1
kind: PersistentVolume
metadata:
  name: esproxy-pv
  labels:
    app: esproxy-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /opt/kubevolume/esdata
