apiVersion: apps/v1
kind: Deployment
metadata:
  name: guppy-deployment
spec:
  selector:
    matchLabels:
      app: guppy
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: guppy
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - guppy
              topologyKey: "kubernetes.io/hostname"
      automountServiceAccountToken: false
      volumes:
        - name: guppy-config
          configMap:
            name: guppy-manifest
        - name: cert-volume
          secret:
            secretName: "guppy-certs"
        - name: ca-volume
          secret:
            secretName: "guppy-service-ca"
        - name: wait-script
          configMap:
            name: guppy-wait
            defaultMode: 0755
      containers:
        - name: guppy
          image: quay.io/cdis/guppy:2021.03
          command:
          - /usr/bin/wait_for_esproxy.sh
          args:
          - node 
          - --max-http-header-size 
          - "16000"
          - dist/server/server.js
          livenessProbe:
            httpGet:
              path: /_status
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /_status
              port: 8000
          ports:
          - containerPort: 8000
          env:
          - name: GUPPY_PORT
            value: "8000"
          - name: GUPPY_CONFIG_FILEPATH
            value: /guppy/guppy_config.json
          - name: GEN3_ES_ENDPOINT
            value: http://esproxy-service:9200
          - name: GEN3_ARBORIST_ENDPOINT
            value: http://arborist-service
          volumeMounts:
            - name: guppy-config
              readOnly: true
              mountPath: /guppy/guppy_config.json
              subPath: guppy_config.json
            - name: "cert-volume"
              readOnly: true
              mountPath: "/mnt/ssl/service.crt"
              subPath: "service.crt"
            - name: "ca-volume"
              # See https://askubuntu.com/questions/645818/how-to-install-certificates-for-command-line
              readOnly: true
              mountPath: "/usr/local/share/ca-certificates/cdis-ca.crt"
              subPath: "ca.pem"
            - name: wait-script
              readOnly: true
              mountPath: /usr/bin/wait_for_esproxy.sh
              subPath: wait_for_esproxy.sh
          resources:
            requests:
              cpu: 0.5
              memory: 1024Mi
            limits:
              cpu: 1
              memory: 2400Mi  