---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arborist-deployment
spec:
  selector:
    matchLabels:
      app: arborist
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: arborist
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - arborist
              topologyKey: "kubernetes.io/hostname"
      automountServiceAccountToken: false
      volumes:
      - name: config-volume
        configMap:
          name: arborist-setup
      containers:
      - name: arborist
        image: quay.io/cdis/arborist:2021.03
        imagePullPolicy: Always
        env:
        - name: JWKS_ENDPOINT
          value: "http://fence-service/.well-known/jwks"
        - name: PGDATABASE
          value: arborist_db
        - name: PGUSER
          value: arborist_user
        - name: PGPASSWORD
          value: arborist_pass
        - name: PGHOST
          value: postgres-service
        - name: PGPORT
          value: "5432"
        - name: PGSSLMODE
          value: disable
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 10
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          readOnly: true
          mountPath: /go/src/github.com/uc-cdis/arborist/arborist_setup.sh
          subPath: arborist_setup.sh
        resources:
          requests:
            cpu: 0.4
            memory: 1200Mi
          limits:
            cpu: 0.8
            memory: 2400Mi
        command:
        - /bin/bash
        - /go/src/github.com/uc-cdis/arborist/arborist_setup.sh